baseURL = "http://example.org/"
languageCode = "en-us"
title = "Van Ribeiro"
theme = "vanribeiro"
disqus = "vanribeiro-github-io"

[Menus]
    main = [
        {Name = "Encontre-me!", URL = "https://vanribeiro.github.io/encontre-me.html"},
        {Name = "Portfólio", URL = "https://vanribeiro.github.io/portfolio.html"},
        {Name = "Currículo", URL = "https://vanribeiro.github.io/curriculo/curriculo-vanessa-ribeiro.html"}
    ]
